# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PV(object):
    def setupUi(self, PV):
        PV.setObjectName("PV")
        PV.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(PV)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chart = PlotWidget(self.centralwidget)
        self.chart.setObjectName("chart")
        self.horizontalLayout_2.addWidget(self.chart)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setObjectName("start")
        self.horizontalLayout_3.addWidget(self.start)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setObjectName("stop")
        self.horizontalLayout_3.addWidget(self.stop)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        PV.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PV)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        PV.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PV)
        self.statusbar.setObjectName("statusbar")
        PV.setStatusBar(self.statusbar)

        self.retranslateUi(PV)
        QtCore.QMetaObject.connectSlotsByName(PV)

    def retranslateUi(self, PV):
        _translate = QtCore.QCoreApplication.translate
        PV.setWindowTitle(_translate("PV", "PV"))
        self.back.setText(_translate("PV", "Назад"))
        self.start.setText(_translate("PV", "Старт"))
        self.stop.setText(_translate("PV", "Стоп"))
from pyqtgraph import PlotWidget
